gen_path: "models/Gen_basic.trc"
dis_path: "models/Dis_basic.trc"

image_rate: 100
num_epoch: 1
nc: 1  # Number of chanels
nz: 100  # Size of z latent vector (i.e. size of generator input)
ngf: 64  # Size of feature maps in generator
ndf: 64  # Size of feature maps in discriminator
lr: 0.0002
beta1: 0.5  # Beta1 hyperparam for Adam optimizers
real_label: 1
fake_label: 0
