gen_path: "models/Gen_vaegan.trc"
dis_path: "models/Dis_vaegan.trc"
enc_path: "models/Enc_vaegan.trc"

image_rate: 5
num_epoch: 2
nc: 1
nz: 100
ngf: 64
ndf: 64
lr: 0.0002
image_size: 48
beta1: 0.5
real_label: 1
fake_label: 0
lambda_val: 0.1
num_labs: 7